### ISSUE TITLE
kyro不支持下面的序列化，该如何处理

### ISSUE THREAD

**Issue by lvdelu** [chengdedeng/blog#25]
private  Class<? extends StatMetric> metricClazz;

**Comment by chengdedeng** [comment]
Java的范型编译之后会类型擦出，在序列化的时候它不知道具体对应哪个类。我知道很多JSON库是支持该特性的，kyro的特性导致它在这方面的支持可能比较弱一点，你可以到stackoverflow中搜一下。

**Comment by lvdelu** [comment]
没有找到啊？麻烦给个地址
